#! /bin/bash

# uninstall old versions

sudo apt-get remove docker docker-engine docker.io containerd runc
# install docker-ce
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io
